#ifndef SYSTIMER_H
#define SYSTIMER_H

#ifdef RPI2
    #define SYSTIMER_BASE 0x3F003000
#else
    #define SYSTIMER_BASE 0x20003000
#endif

#define SYSTIMER_CONTROL       SYSTIMER_BASE
#define SYSTIMER_COUNTER_LOW   SYSTIMER_BASE+0x04
#define SYSTIMER_COUNTER_HIGH  SYSTIMER_BASE+0x08
#define SYSTIMER_COMPARE0      SYSTIMER_BASE+0x0C
#define SYSTIMER_COMPARE1      SYSTIMER_BASE+0x10
#define SYSTIMER_COMPARE2      SYSTIMER_BASE+0x14
#define SYSTIMER_COMPARE3      SYSTIMER_BASE+0x18

#endif
